# Conclusions and further work
\chaptermark{Conclusions and further work}

## Introduction

In this thesis, I have presented the findings from a clinical study with two broad aims: first, to describe the presentation, aetiology, outcomes and determinants of outcomes in adults in Blantyre, Malawi; and second, to describe colonisation with ESBL-E as sepsis survivors pass from the hospital to the community, and an analysis to identify determinants of carriage. In Chapter one,  I presented a hypothesis that it is possible to improve outcomes for patients with sepsis whilst reducing over-reliance on broad spectrum antibacterials such as ceftriaxone, and hence minimise pressure for the development of antimicrobial resistance. In this chapter I review the findings of this thesis in the context of this hypothesis, and suggest directions for future work.

## Summary of findings

The clinical study of sepsis presented in Chapters 3 and 4 confirm that sepsis is Malawi is very different from sepsis in high-income low-HIV and low-TB prevalence settings from where most studies of sepsis arise. Malaeian patients presenting with sepsis, as elsewhere in sSA, are young, and predominantly HIV-infected. They have been sick for a longer period of time (median 7 days) with clinical syndromes/pathogens not typically associated with fulminant disease in high income settings i.e. _Salmonella_ Typhi bloodstream infection, disseminated tuberculosis, and malaria. The easily modifiable determinants of sepsis outcome that have received so much attention in high-income settings - rapid administration of antibacterials and fluids - were not associated with survival in this cohort. This could be due to a true lack of effect, or to underpowering, but it highlights the need for data from sSA to guide the development of sepsis protocols relevant to sSA.

TB was the commonest cause of sepsis identified in the cohort - 34% of participants had at least one positive diagnostic test for TB, rising to 50% in HIV-infected participants - and administration of antituberculous chemotherapy showed an association with survival (RR 1.25 for survival [95% CI 0.04-1.51] in propensity-score analysis). Confidence intervals are large, but the effect size for benefit in the anaemic (for example) is larger than that in those with confirmed TB, suggesting that there may be a role for empiric TB therapy in sepsis, but the role of TB therapy in the treatment of the critically unwell is unknown, and must be the focus of further work (see below). The 28-day mortality of sepsis in Blantyre was lower than expected at 18% (95% CI 13-23%), and lower than historical mortality estimates from across the continent described in Chapter 1. The reasons for this are speculative, but ART coverage was high compared to historical cohorts. Despite this, it seems likely that the presentation of sepsis in a number of participants in this study was a manifestation of ART failure. Few participants were switched to second-line therapy, and longer-term mortality (beyond 28 days) was significant in the HIV-infected with a near doubling of mortality from 19% (95% CI 13-26%) at 28 days to 36% (95% CI 28-45%) at 180 days.

In Chapter 5, I presented details of gut mucosal colonisation with ESBL-E in sepsis participants but also antibiotic-unexposed hospital inpatients and community members. Community carriage is common, with a baseline community carriage prevalence of 28% (95% CI 20-38%) and factors associated with baseline carriage (household crowding, unprotected water source and sample collection during rainy season) strongly suggest that within-household and environmental transmission routes are important. Co-trimoxazole preventative therapy (CPT) was also associated with ESBL-E carriage at baseline, as was recent hospitalisation. In antibacterial-exposed inpatients there is a dramatic rise in ESBL-E colonisation prevalence, which is not seen in the antibacterial-unexposed. As expected, broad spectrum antibacterial exposure, largely ceftriaxone, was near-universal in the sepsis cohort with a median 5 days (IQR 3-7) of exposure, but this is dwarfed in person-days of exposure by co-trimoxazole. This is perhaps unsurprising given that co-trimoxazole is mandated lifelong for all people loving with HIV in Malawi, but the magnitude of the difference is almost two orders of magnitude: 14,447 person days of exposure of co-trimoxazole versus 997 for ceftriaxone. 

Genomic analyses using whole genome sequencing of a subset of cultured isolates suggests that there is reasonably unrestricted mixing of _E. coli_ strains at multiple spatial levels: between Malawi and the the rest of the world, and between the hospital and community. The exception to this is a putative recently arrived high-risk clone, ST410, which shows some healthcare association. The genomic landscape of ESBL in Blantyre is dominated by $bla_{CTX-M}$, reflecting the global situation, and, worryingly, I describe (to my knowledge) the first carbapenemase identified in Enterobacteriaceae in Malawi, a $bla_{NDM-5}$ carried on a globally successful IncX plasmid. Other identified AMR genes reflect the local antibiotic pressures: in particular, co-trimoxazole resistance determinants are near-ubiquitous. Using WGS as a high-resolution typing tool by clustering bacteria core genes and ESBL-containing contigs I show that it is the ESBL contig-bacteria combination that is conserved within patients, suggesting that the unit of transmission in this system is the bacteria, rather than transfer of MGE. I also demonstrate significant turnover of ESBL-E: beyond 35 days, two samples from within a patient are no more likely to contain the same ESBL contig-bacteria combination than due to chance alone.

Finally, I develop and fit two-state continuous-time Markov models in a Bayesian framework to understand the drivers of ESBL-E carriage in this cohort. I find that hospitalisation increases both ESBL-E acquisition and loss with a net effect of rapid ESBL-E acquisition following hospitalisation. Antibacterial exposure acts to prolong carriage by reducing the rate of loss, and I find support in the data for a prolonged post-antibiotic effect with a long half-life of 43 days (95% CI 15-98 days) that acts to prolong carriage long after antibacterial exposure has finished. Simulations show that there is synergy between hospitalisation and antibacterial exposure which produces the sharp rises in ESBL-E colonisation prevalence, but also that the post-antibiotic effect results in significantly prolonged carriage. In addition, the post-antibiotic effect means that short courses of antibacterials have, in terms of ESBL-E carriage, similar effects to prolonged courses, with significant implications for antimicrobial stewardship. Co-trimoxazole preventative therapy seems to be a significant driver of long-term carriage.

## Conclusions and future research priorities

In light of these findings, is it possible to provide suggestions for antibiotic strategies for sepsis in Blantyre that will improve outcomes whilst minimising acquisition of ESBL-E? I suggest not for severely unwell patients that urgently need antimicrobials: the post-antibiotic effect from the longitudinal models means that a short course of antibacterials (e.g. 2 days) has a similar effect to a longer one (e.g more than 7 days), at least in terms of ESBL-E acquisition, and that  all the considered antibacterials seem to have a similar effect of ESBL-E carriage. The models imply therefore that the antimicrobial stewardship intervention to best minimise ESBL-E carriage is to avoid antibacterials altogether. This is not feasible in these very unwell patients, in whom initial empiric antimicrobials is certainly appropriate, however health systems interventions that support the safe restriction of antimicrobials in patients that do not require them such as patients with viral respiratory tract infections (e.g. improved point of care diagnostics) may achieve this effect. The data I present therefore highlight several areas of further research priority. 

**1. Identification of TB and initiation of antituberculous chemotherapy at presentation**

There is a strong suggestion that antituberculous chemotherapy may improve outcomes in sepsis in Blantyre, but the best ways to deploy this therapy in the critically unwell are unknown. Whether empiric therapy is warranted depends on the diagnostic ability of the available tests for TB and, since performing the testing for urinary lipoarabinomannan (uLAM) that I have presented here, a more sensitive uLAM assay has become available. To truly make recommendation for the use of TB therapy in sepsis, it is necessary to understand the impact of this improved diagnostic on the analysis I have presented. To that end the stored urines from this study will be tested with the new, more sensitive fujiLAM assay. To understand the reasons for the unexpectedly low prevalence of TB bloodstream infection, these will be tested alongside Xpert Ultra testing of stored blood samples. These results will allow clear recommendations for the use of TB therapy in sepsis, which can be taken forward for testing in clinical trials. The pharmacokinetics of standard quadruple antituberculous therapy in the critically unwell are not, however, well described and pharmacokinetic studies in this population, perhaps as part of clinical trials of TB therapy in sepsis, should be undertaken. 

**2. Investigation of post 28-day mortality in HIV-infected participants**

The cause of the significant post-28 day mortality in HIV-infected participants warrants further scrutiny. This requires more in depth clinical follow up than was possible in this study, but a starting point is to clearly define whether the participants in this study who seem to be failing ART had true HIV virological failure. This can be achieved with retrospective testing of stored blood samples. The global success of ART roll out means that failure of first line therapy is likely to be increasingly common, and strategies to  rapidly identify ART failure and switch people to second line may be needed. It may be that hospital admissions with severe infection provide such an opportunity. Demonstrating virologic failure is a necessary first step.

**3. Understand the biology of post-antibiotic selection pressure for ESBL-E colonisation** 

The key finding from the longitudinal modelling of ESBL-E carriage is that there is a prolonged post-antibiotic effect. It is this that leads me to state that the overall hypothesis of this thesis - that we can improve sepsis outcomes whilst minimising ESBL-E acquisition -  cannot be supported with the available data, because a shorter course of antibacterials in the hospitalised was predicted to have a similar effect to a longer one. However, this also makes the post antibiotic effect an attractive target for intervention. I have demonstrated an association, but there is a need to understand the biology. How is it mediated? I suggest that a likely candidate, and a good starting point, is the composition of the gut microbiota. The effect of even short courses of antimicrobials on the microbiota can be profound, and antibacterial-mediated destruction of microbiota colonisation resistance to ESBL-E could certainly cause the effects I have described. Total stool DNA has been extracted in real time from the participants in the study, and shotgun metagenomic sequencing of these samples can be used to start to assess the role of the microbiota in mediating the post antibiotic effect: changes in the microbiota predictive of ESBL-E colonisation (or ESBL-E abundance) and identification of taxa associated with non-colonisation with ESBL-E at baseline could provide an understanding of mechanism, Ultimately, this could suggest microbiota-modulating therapies to promote colonisation resistance to ESBL-E.

Metagenomics can also address one of the limitations of the genomic analysis: that only one colony pick from each participant at each time point was sequenced, so the total within-host ESBL-E diversity is unknown. Metagenomics can not tell the whole story, however, as it can not place AMR genes within bacteria, but must be supplemented by further colony picks for whole genome sequencing. Stored plate sweeps from all the participants in the study can facilitate this. In addition, the work is already under way to sequence _E. coli_ from all remaining samples and one _K. pneumoniae_ from all samples in which this species was identified, using short-read sequencing. This will allow comparison of the AMR determinants carried within these two species within one host, over time, and allow an understanding of the extent to which horizontal gene transfer is occurring. To truly define the MGE upon which ESBL genes are carried requires long-read sequencing. This work is also under way on a number of representative isolates. This will also allow an analysis of the genomic environment of the apparently inactive _catB4_ genes that were frequently seen in this analysis. 

**4. Re-evaluate co-trimoxazole preventative therapy protcols in an era of rising Gram-negative resistance**

Finally, my analysis of determinants of ESBL-E carriage suggests that co-trimoxazole preventative therapy (CPT) may be a major driver of AMR carriage. The exact mechanism of mortality benefit of CPT is unknown and it may be that its benefit is driven by e.g. antimalarial activity; studies to address this hypothesis are underway (e.g. TSCQ trial ClinicalTrials.gov identifier NCT01650558). The fact that co-trimoxazole resistance is near ubiquitous in the ESBL _E. coli_ in this study along with the modelling findings suggests that CPT may be having strong unintended selection pressure for ESBL-E. In an era of rising Gram-negative resistance I suggest that in some cases the benefits of this therapy may be outweighed by its risks and that perhaps a more nuanced approach to CPT usage than lifelong treatment for all people living with HIV is required, which is still sufficiently pragmatic to be useful in sSA. This would require clinical studies examining the outcomes of strategies such as stopping CPT once well established on ART, but AMR endpoints (such as ESBL-E carriage) should be included in such trials.

