--- 
title: "Causes and consequences of adult sepsis in Blantyre, Malawi"
subtitle:  | 
  |  -
  |  
  | Thesis submitted in accordance with the requirements of the Liverpool School of Tropical Medicine for the degree of Doctor in Philosophy by Joseph Michael Lewis
  | 
  | September 2019
output: bookdown::pdf_book
fontsize: 11pt
geometry: "left=4cm, right=2.5cm,top=2.5cm,bottom=2.5cm" 
lof: False
lot: False
documentclass: book
bibliography: ["/Users/joelewis/Documents/bib/library.bib"]
csl: bmj.csl
biblio-style: apalike
link-citations: yes
description: "Joe's thesis. Yikes!"
toc: False
header-includes:
   \usepackage{array}
   \usepackage{threeparttablex}
   \usepackage{longtable}
   \usepackage{float}
   \usepackage{booktabs}
   \usepackage{setspace}
   \usepackage{textcomp}
   \usepackage{pdflscape}
   \usepackage[font={small}]{caption}
   \raggedbottom
   \onehalfspacing
   
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r child = 'misc_rmds/dedication.Rmd'}
```

```{r child = 'misc_rmds/collaborators.Rmd'}
```

```{r child = 'misc_rmds/abstract.Rmd'}
```

```{r child = 'misc_rmds/ackn.Rmd'}
```

```{r child = 'misc_rmds/pubs.Rmd'}
```

```{r child = 'misc_rmds/abvs.Rmd'}
```

```{=latex}
\tableofcontents
\listoffigures
\listoftables
```




