# Abstract {-}

Sepsis, defined as a life-threatening organ dysfunction triggered by infection, carries a high mortality. Recent improvements in outcome high-income settings have been driven by prompt antimicrobial therapy and fluid resuscitation but mortality remains disproportionately high in low-resource settings like sub-Saharan Africa (sSA). Therapy here often consists of empiric, prolonged courses of broad-spectrum antimicrobials, especially third generation cephalosporins like ceftriaxone, which may be driving the rise of ceftriaxone-resistant extended-spectrum $\beta$-lactamase producing Enterobacteriaceae (ESBL-E). However the aetiology of sepsis in sSA is far from clear, and in this thesis I conjecture that it may be possible to improve outcomes in sepsis whilst reducing selection pressure for ESBL-E, with novel, targeted, antimicrobial strategies tailored to the pathogens that are truly causing sepsis here.

To that end, I present findings from a clinical cohort study of sepsis in Blantyre, Malawi, with two aims: first, a description of the presentation and outcomes of sepsis in Blantyre, with a focus on aetiology and an analysis of the determinants of mortality; and secondly, a description of the gut mucosal carriage of ESBL-E in sepsis survivors (as well as antibiotic unexposed inpatient and community controls) as they pass through the hospital to identify determinants of carriage. An expanded package of diagnostic tests was used to define sepsis aetiology, and serial stool sampling with selective culture for ESBL-E used to define ESBL-E carriage. I use whole-genome sequencing of cultured ESBL _E. coli_ to track bacteria and mobile genetic elements within participants over time, and continuous time Markov models to provide insight into the drivers of carriage.

I find that the majority of participants with sepsis are young, and HIV-infected. Tuberculosis (TB) dominates as a cause of sepsis, and there is an association of receipt of antituberculous chemotherapy with survival that suggests an expanded role for TB therapy in these very unwell patients may be beneficial. Sepsis mortality seems to have improved compared to historic cohorts, but post 28-day mortality in the HIV-infected is significant. 

At baseline ESBL-E colonisation is common, with 49% of participants with sepsis colonised on the day of admission, and further rapid increase in colonisation prevalence following admission and antibacterial exposure. Associations of baseline colonisation - household crowding and unprotected water sources - suggest both within-household and environmental routes of transmission are important. Genomic analysis suggest unrestricted mixing of ESBL _E. coli_ at multiple spatial levels and rapid turnover within the individual, perhaps suggestive of frequent re-exposure. 

Longitudinal modelling provides insight into ESBL-E carriage dynamics: hospitalisation and antibacterial exposure act synergistically to bring about rapid and prolonged carriage driven, in part, by a significant post-antibiotic effect. This effect means that antibacterials act to prolong carriage long after antibacterial exposure stops.  In terms of ESBL-E carriage, short courses of antibacterials have a similar effect to longer courses, such that the conjecture of the thesis is likely to be false: it may not be possible to reduce ESBL-E carriage by truncating courses of ceftriaxone. Nevertheless, the post-antibiotic effect deserves further scrutiny to understand the mechanism and as a potential therapeutic target. In addition, the modelling approach suggests cotrimoxazole preventative therapy (CPT) may be a significant driver of long-term ESBL-E carriage, and I suggest that a more nuanced approach to its deployment may be necessary in an era of increasing Gram-negative resistance.

